// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goujbvcbxqugjcjoakmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWpidmNieHF1Z2pjam9ha210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODMxNjcsImV4cCI6MjA2Njc1OTE2N30.aKqE1tJ-iSKWF7XFGwAbPZjpKgZI16eEmz96B5lGuDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);